INSERT INTO league (league_name, league_country) VALUES ("Premier League", "England");
INSERT INTO league (league_name, league_country) VALUES ("La Liga", "Spain");
INSERT INTO league (league_name, league_country) VALUES ("FA Cup", "England");
INSERT INTO league (league_name, league_country) VALUES ("Champions League", "Europe");
INSERT INTO league (league_name, league_country) VALUES ("Europa League", "Europe");
INSERT INTO league (league_name, league_country) VALUES ("Copa Del Rey", "Spain");
INSERT INTO league (league_name, league_country) VALUES ("Coupe de France", "France");
INSERT INTO league (league_name, league_country) VALUES ("DFB-Pokal", "Germany");
INSERT INTO league (league_name, league_country) VALUES ("Ligue 1", "France");
INSERT INTO league (league_name, league_country) VALUES ("Bundesliga", "Germany");

INSERT INTO team_league (team_id, league_id) VALUES (3,1);
INSERT INTO team_league (team_id, league_id) VALUES (3,5);
INSERT INTO team_league (team_id, league_id) VALUES (3,3);
INSERT INTO team_league (team_id, league_id) VALUES (4,1);
INSERT INTO team_league (team_id, league_id) VALUES (4,3);
INSERT INTO team_league (team_id, league_id) VALUES (5,2);
INSERT INTO team_league (team_id, league_id) VALUES (5,4);
INSERT INTO team_league (team_id, league_id) VALUES (5,6);
INSERT INTO team_league (team_id, league_id) VALUES (6,1);
INSERT INTO team_league (team_id, league_id) VALUES (6,3);
INSERT INTO team_league (team_id, league_id) VALUES (6,4);
INSERT INTO team_league (team_id, league_id) VALUES (7,8);
INSERT INTO team_league (team_id, league_id) VALUES (7,10);
INSERT INTO team_league (team_id, league_id) VALUES (8,2);
INSERT INTO team_league (team_id, league_id) VALUES (8,6);
INSERT INTO team_league (team_id, league_id) VALUES (8,4);
INSERT INTO team_league (team_id, league_id) VALUES (9,4);
INSERT INTO team_league (team_id, league_id) VALUES (9,1);
INSERT INTO team_league (team_id, league_id) VALUES (9,3);
